AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
Documentation:
  Enabled: false
Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false
Style/IfUnlessModifier:
 MaxLineLength: 120
Style/StringLiterals:
  EnforcedStyle: single_quotes
