language: ruby
rvm:
- 2.1.2
env:
  matrix:
  - DB=sqlite
  global:
    secure: A1HqAHXQe8UvKbHJxa7OR1RARDj/ZMFNy1snqW4Ow0E95bQqgee5DGDiQurtsYk2XX79B0fxvI1/YnjLyIg0foQoksMmPp4hrW6idFtRCYasFB7YLZmuavNG+M/VSdXhi2IN2s/lk8tVclu4ip4xGq0mEbP8geUJ02YBh324lcc=
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test
deploy:
  provider: heroku
  # strategy: git
  api_key:
    secure: j9UTj6i3X61G8OsxuAGAy1KaARAYKqC6jc9LarYw2ipd4hXh2TQ2V/Glo1b0sIfvMAnAeOjEV851lyJ4Fl9S2W9rvhCYskNNOMavpeTr3Mreyfw2//y9ZpNKcShSwoxVfBcJBk49+GVqDeIMZ8Yv22xwJmc4ebiMgzOlTaDWBY8=
  app: lit-everglades-6352
  on: master
