TRUNCATE TABLE service_definitions;
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Aceite', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Aceites de todas las marcas', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Agrícola', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Aire acondicionado', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Alineación', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Alineación de dirección', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Alineado de Direcciones', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Amortiguadores', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Aparcamiento', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Asistencia', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Asistencia 24 horas', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Baterias', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Bolas de Remolque', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Cambio de Aceite', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Cambio de Aceite y Filtros', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Cambio de amortiguadores', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Cambio de frenos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Camión', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Car audio', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Carga de Aire Acondicionado', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Carrocería y Pintura', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Chapa', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Chapa y pintura', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Chófer al Taller', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Climatización', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Diagnosis', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Diagnosis electrónica', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Diagnosis, electricidad, mecánica correctiva y preventiva', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Distribución', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Electricidad', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Electricidad Electrónica', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Electrónica', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Embragues', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Equipos de diagnosis para inyección de gasolina y diesel', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Escape', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Escapes', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Escobillas', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Especialistas en neumáticos RunFlat', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Filtros', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Frenos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Garantía Mecánica Nacional', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Garantía Pintura por Vida', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Hotel neumáticos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Inflado con nitrógeno', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Inyección', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('ITV', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Kit de distribución', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Lavadero de Turismos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Lavado', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Lavado de bajos de carrocería', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Lavado del vehiculo', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Lavado y tratamiento de tapicerías', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Limpieza', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Limpieza del Vehículo', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Limpieza integral', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Limpieza ozono', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Línea de Pre-ITV  Planchas detector de olguras, frenómetro, reglafaros, opacímetro, analizador gases, etc', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Llantas', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Lunas', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Mecánica', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Mecánica general', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Mecánica profunda', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Mecánica Rápida', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Mecanica_general', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Mecanica_rapida', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Montaje (incl. válv. estándar, equil. y nitrógeno)', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Neumáticos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Pastillas de Freno', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Pintura', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Plan de Mantenimiento EXCELLENT', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Plan de Mantenimiento EXPRESS', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Plan de Mantenimiento PREMIUM', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Pre-ITV', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Precio mínimo garantizado en Neumáticos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Pre_itv', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Pulimento de faros', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Recogida a domicilio', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Recogida y Entrega', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Renting', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Reparacion de Neumaticos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Reparación de pinchazos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Revisión', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Revisión anual gratuita de Seguridad', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Revisión Pre-ITV', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Rotación', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Sábados Julio y Agosto: Cerrado', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Sala de espera', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Servicio 24 horas', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Servicio de recogida', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Servicio de recogida y entega', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Servicio rápido', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Sonido', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Superficie', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Suspensión', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Suspensiones', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Tienda', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Tubos de Escape', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Tuning', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Vehículo de Sustitución', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Vehículo industrial agrario', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Vehículos Clásicos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Venta de Accesorios', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Venta y Montaje de Neumaticos', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Venta y Montaje de s de Aluminio', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Visibilidad', NOW(), NOW());
INSERT INTO service_definitions(name, created_at, updated_at) VALUES ('Zona w', NOW(), NOW());